### ISSUE TITLE
Crear Mapa de sitio

### ISSUE THREAD

**Issue by Espinedoa** [Espinedoa/Programacion-FULL-STACK#6]

**Comment by Espinedoa** [comment]
Fran, crear mapa de sitio

**Comment by fmerroz** [comment]
![mapa de sitio](https://user-images.githubusercontent.com/106285052/200178757-a063cce1-7d95-49c8-8774-78b223720d77.jpg)

**Comment by fmerroz** [comment]
idea del diseño del mapa de sitio
